mongo:
  url: mongodb+srv://chaitanya:fofx@munukutla-mongo-cluster-kt0qc.mongodb.net/readWriteAnyDatabase@admin?retryWrites=true
  collections:
    users: users
    events: events
    registrations: eventsreg